// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfj_bC_gC_pwIvUVx_WOD57pLI6DZs94',
    appId: '1:358785041168:web:ecc996680e7632a104db95',
    messagingSenderId: '358785041168',
    projectId: 'graphs1-602ab',
    authDomain: 'graphs1-602ab.firebaseapp.com',
    databaseURL: 'https://graphs1-602ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'graphs1-602ab.appspot.com',
    measurementId: 'G-FKT72KQ17F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASk9cD60gobyshuKytxUETyIl8q5aGzns',
    appId: '1:358785041168:android:89c16e4f2d0e6ff204db95',
    messagingSenderId: '358785041168',
    projectId: 'graphs1-602ab',
    databaseURL: 'https://graphs1-602ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'graphs1-602ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfdgmoI6mLe8ksRKFiC0AHGMs1inKOoNU',
    appId: '1:358785041168:ios:25cab465df89c91504db95',
    messagingSenderId: '358785041168',
    projectId: 'graphs1-602ab',
    databaseURL: 'https://graphs1-602ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'graphs1-602ab.appspot.com',
    iosClientId: '358785041168-9jeo4dkm4ej688hk03vd66hlff8o8av4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChartJson',
  );
}
